'use client';

import { FormEvent, useState } from 'react';

export default function ProfileSettingsForm({ initialName }: { initialName: string }) {
  const [name, setName] = useState(initialName); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); try { const response = await fetch('/api/auth/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, currentPassword, newPassword }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCurrentPassword(''); setNewPassword(''); setMessage('Profile updated.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update profile.'); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-5"><label className="form-field"><span className="form-label">Display name</span><input className="form-input" value={name} onChange={event => setName(event.target.value)} required minLength={2} maxLength={100} /></label><div className="border-t border-slate-100 pt-5"><h2 className="text-sm font-semibold text-slate-800">Change password</h2><p className="mt-1 text-xs text-slate-500">Leave both fields empty to keep the current password.</p><div className="mt-4 grid gap-4"><label className="form-field"><span className="form-label">Current password</span><input className="form-input" type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} autoComplete="current-password" /></label><label className="form-field"><span className="form-label">New password</span><input className="form-input" type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} autoComplete="new-password" minLength={12} /><span className="text-xs text-slate-500">Use at least 12 characters.</span></label></div></div>{error && <p className="text-sm text-red-600" role="alert">{error}</p>}{message && <p className="text-sm text-emerald-700" role="status">{message}</p>}<div className="form-actions"><button className="primary-button" disabled={loading}>{loading ? 'Saving...' : 'Save profile'}</button></div></form>;
}
