import Link from 'next/link';
import { ArrowRight, Check, ChevronDown, Sparkles } from 'lucide-react';
import { currentUser } from '../../../lib/auth';
import SubscribeButton from './SubscribeButton';

const productData = {
  salon: { name: 'Salon OS', eyebrow: 'For salons & studios', headline: 'More time for the work people come back for.', description: 'Appointments, clients, staff, services, and daily operations in one calm workspace.', accent: 'mint', features: ['Appointments that stay in sync', 'Client relationships with context', 'Staff and service management', 'Reports for better decisions'] },
  inventory: { name: 'Inventory OS', eyebrow: 'For distribution teams', headline: 'Every product accounted for. Every decision clearer.', description: 'Keep products moving, teams aligned, and your supply operation ready for what is next.', accent: 'blue', features: ['Stock visibility across locations', 'Purchases and sales in one flow', 'Supplier and customer records', 'Orders that do not get lost'] },
  pg: { name: 'PG OS', eyebrow: 'For property operators', headline: 'Run the property. Know the people.', description: 'A simpler way to manage rooms, residents, rent, payments, and everything between.', accent: 'gold', features: ['Rooms, beds, and occupancy', 'Resident profiles with context', 'Rent and payment tracking', 'Complaints and maintenance'] },
} as const;

export function generateStaticParams() { return Object.keys(productData).map((slug) => ({ slug })); }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = productData[slug as keyof typeof productData] ?? productData.salon;
  const user = await currentUser();
  return <main className="public-site"><nav className="public-nav"><Link href="/" className="public-logo"><span>F</span> FYtech</Link><div className="public-nav-links"><Link href="/#products">Products</Link><Link href="/#platform">Platform</Link><Link href="/#pricing">Pricing</Link></div><div className="public-nav-actions"><Link href={user ? '/' : '/login'} className="public-login">{user ? 'Back to FYtech' : 'Sign in'}</Link><Link href={user ? '/app' : '/signup'} className="public-nav-cta">{user ? 'My workspace' : 'Get started'} <ArrowRight size={15} /></Link></div></nav><section className={`product-hero product-hero-${product.accent}`}><div className="product-hero-copy"><div className="public-eyebrow"><Sparkles size={14} /> {product.eyebrow}</div><h1>{product.headline}</h1><p>{product.description}</p><div className="public-hero-actions"><SubscribeButton slug={slug} signedIn={Boolean(user)} /><Link href="/#products" className="public-text-link">View all products <ChevronDown size={15} /></Link></div></div><div className="product-mock"><div className="mock-top"><span>{product.name}</span><span>Today · Overview</span></div><div className="mock-heading">Your operation, in view.</div><div className="mock-kpis"><div><span>Today</span><strong>24</strong><small>active items</small></div><div><span>On track</span><strong>92%</strong><small>this week</small></div><div><span>Next</span><strong>08</strong><small>to review</small></div></div><div className="mock-lines"><i /><i /><i /><i /></div></div></section><section className="product-feature-section"><div><div className="public-eyebrow">Everything in one view</div><h2>Designed around<br /><em>how you work.</em></h2><p>Less time finding information. More time making the next good decision.</p></div><div className="product-features">{product.features.map((feature) => <div key={feature}><span><Check size={15} /></span><strong>{feature}</strong><p>Clear, connected, and ready for your team.</p></div>)}</div></section><section className="product-cta"><div className="public-eyebrow">Start with clarity</div><h2>Your work deserves<br /><em>better software.</em></h2><SubscribeButton slug={slug} signedIn={Boolean(user)} /></section><footer className="public-footer"><div><Link href="/" className="public-logo"><span>F</span> FYtech</Link><p>Business software, connected.</p></div><div className="footer-bottom">© 2026 FYtech. Built for businesses in motion.</div></footer></main>;
}