import { Bell, LockKeyhole, Settings, ShieldCheck } from 'lucide-react';

export default function SettingsPage() {
  return (
    <div>
      <div className="page-header"><div><div className="page-eyebrow">Workspace controls</div><h1 className="page-title">Settings</h1><p className="page-description">Configure how your FYtech platform is presented and operated.</p></div></div>
      <div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections"><a href="#general">General</a><a href="#notifications">Notifications</a><a href="#security">Security</a></nav><section className="panel"><div className="panel-body"><div className="settings-section" id="general"><div className="flex items-center gap-3"><Settings size={18} className="text-teal-700" /><div><h2>General</h2><p>Core identity for your platform workspace.</p></div></div><div className="form-grid"><label className="form-field"><span className="form-label">Workspace name</span><input className="form-input" defaultValue="FYtech" /></label><label className="form-field"><span className="form-label">Default timezone</span><select className="form-input" defaultValue="Asia/Kolkata"><option>Asia/Kolkata</option><option>UTC</option><option>America/New_York</option></select></label></div></div><div className="settings-section" id="notifications"><div className="flex items-center gap-3"><Bell size={18} className="text-teal-700" /><div><h2>Notifications</h2><p>Choose which platform events reach your admin team.</p></div></div><label className="flex items-center gap-3 text-sm text-slate-600"><input type="checkbox" defaultChecked className="h-4 w-4 accent-teal-700" /> Notify admins about new business accounts</label></div><div className="settings-section" id="security"><div className="flex items-center gap-3"><ShieldCheck size={18} className="text-teal-700" /><div><h2>Security</h2><p>Authentication and role-based access controls will live here as identity services are connected.</p></div></div><div className="flex items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600"><LockKeyhole size={17} className="text-slate-400" /> Secure authentication is planned for the next platform foundation phase.</div></div><div className="form-actions"><button className="secondary-button">Discard</button><button className="primary-button">Save changes</button></div></div></section></div>
    </div>
  );
}