import Link from 'next/link';
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDollarSign, Layers3, Menu, ShieldCheck, Sparkles } from 'lucide-react';

const products = [
  { name: 'Salon OS', category: 'For salons & studios', description: 'Appointments, clients, staff, and daily operations in one clear workspace.', href: '/products/salon', accent: 'mint' },
  { name: 'Inventory OS', category: 'For distribution teams', description: 'Know what is moving, what is next, and where every product belongs.', href: '/products/inventory', accent: 'blue' },
  { name: 'PG OS', category: 'For property operators', description: 'Rooms, residents, rent, and maintenance without spreadsheet sprawl.', href: '/products/pg', accent: 'gold' },
];

export default function HomePage() {
  return <main className="public-site"><nav className="public-nav"><Link href="/" className="public-logo"><span>F</span> FYtech</Link><div className="public-nav-links"><a href="#products">Products</a><a href="#platform">Platform</a><a href="#why-fytech">Why FYtech</a><a href="#pricing">Pricing</a></div><div className="public-nav-actions"><Link href="/login" className="public-login">Sign in</Link><Link href="/signup" className="public-nav-cta">Get started <ArrowRight size={15} /></Link></div><button className="public-menu" aria-label="Open menu"><Menu size={20} /></button></nav>
    <section className="public-hero"><div className="public-hero-copy"><div className="public-eyebrow"><Sparkles size={14} /> Business software, connected</div><h1>Powering businesses with <em>smarter software.</em></h1><p>FYtech gives growing businesses specialized tools, one connected platform, and a calmer way to run every day.</p><div className="public-hero-actions"><Link href="#products" className="public-button public-button-dark">Explore products <ArrowRight size={16} /></Link><Link href="#platform" className="public-text-link">See how it works <ChevronRight size={16} /></Link></div><div className="public-proof"><div className="public-proof-avatars"><span>AM</span><span>RK</span><span>JS</span></div><p><strong>Built for the work that matters.</strong><br />A focused platform for ambitious operators.</p></div></div><div className="hero-visual"><div className="hero-visual-top"><span className="live-dot" /> Platform overview <span>•••</span></div><div className="hero-visual-title">Good morning, Maya <span>✦</span></div><div className="hero-chart"><div className="chart-label"><span>Business activity</span><strong>+24.8%</strong></div><div className="chart-bars"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="hero-visual-bottom"><div><span>Active workflows</span><strong>18</strong></div><div><span>Team members</span><strong>42</strong></div><div><span>Products</span><strong>03</strong></div></div></div></section>
    <section className="public-trust"><span>One platform for</span><span>People</span><span>Products</span><span>Places</span><span>Progress</span></section>
    <section className="public-section" id="products"><div className="public-section-heading"><div><div className="public-eyebrow">Made for your world</div><h2>Purpose-built software.<br /><em>Platform-level clarity.</em></h2></div><p>Every FYtech product is designed around a real industry, then connected to the same dependable foundation.</p></div><div className="product-grid">{products.map((product) => <Link href={product.href} className={`product-card product-${product.accent}`} key={product.name}><div className="product-card-icon"><Layers3 size={20} /></div><span className="product-category">{product.category}</span><h3>{product.name}</h3><p>{product.description}</p><span className="product-link">Explore product <ArrowUpRightIcon /></span></Link>)}</div></section>
    <section className="public-band" id="platform"><div className="public-band-copy"><div className="public-eyebrow">The FYtech platform</div><h2>The connective tissue between <em>ambition and action.</em></h2><p>One secure place for your businesses, products, people, subscriptions, and next move.</p></div><div className="feature-list"><div><span className="feature-number">01</span><ShieldCheck size={20} /><div><strong>One trusted foundation</strong><p>Identity, access, and operations that stay in sync as you grow.</p></div></div><div><span className="feature-number">02</span><BarChart3 size={20} /><div><strong>Clarity without the noise</strong><p>Focused dashboards that surface what needs your attention now.</p></div></div><div><span className="feature-number">03</span><CircleDollarSign size={20} /><div><strong>Ready for what is next</strong><p>Start with one product and expand without rebuilding your stack.</p></div></div></div></section>
    <section className="public-section public-pricing" id="pricing"><div className="public-section-heading"><div><div className="public-eyebrow">Simple to start</div><h2>Everything your business needs<br /><em>to move forward.</em></h2></div><p>Choose the product that fits your work. Add more as your business evolves.</p></div><div className="pricing-row"><div><span>Explore the platform</span><strong>Built around your business</strong><p>Get the right tools today, with room to grow tomorrow.</p></div><Link href="/signup" className="public-button public-button-dark">Get started <ArrowRight size={16} /></Link></div></section>
    <footer className="public-footer"><div><Link href="/" className="public-logo"><span>F</span> FYtech</Link><p>Business software, connected.</p></div><div className="footer-links"><div><strong>Explore</strong><a href="#products">Products</a><a href="#platform">Platform</a><a href="#pricing">Pricing</a></div><div><strong>Company</strong><a href="#why-fytech">About FYtech</a><a href="#platform">Contact</a><Link href="/login">Sign in</Link><Link href="/signup">Create account</Link></div></div><div className="footer-bottom">© 2026 FYtech. Built for businesses in motion.</div></footer></main>;
}

function ArrowUpRightIcon() { return <ArrowRight size={15} />; }